### ISSUE TITLE
readdir returns incorrect results when a signal is received

### ISSUE THREAD

**Issue by redneb** [hanwen/go-fuse#191] opened 2017-10-15 19:07 UTC
I have been experiencing a subtle bug when interacting with a `go-fuse` based filesystem. The issue seems to be caused by the following behavior of `go-fuse`: suppose that a process (unrelated to `go-fuse`) tries to read the contents of a directory from a `go-fuse` based filesystem by repeatedly calling `readdir`. If the process receives a signal while on a `readdir` call, then a directory entry is skipped and thus the process receives an incorrect list for the contents for the directory.

To simulate this situation I wrote a small C program attached below. The program works as follows: it first arranges for the `SIGVTALRM` signal to be delivered to the process every 10ms. It then counts the number of files contained in the specified directory. Finally, it counts these files again in a loop and it keeps doing that for as long as it gets the same count. Normally, if the directory does not get modified, the count should remain the same and thus the loop should run forever. But this doesn't happen with `go-fuse` based filesystems.

To run the program, simple specify a directory to run it on: `ls-count /path/to/dir`. If the directory does not get modified, the program will run indefinitely without printing anything. This is the expected behavior.

I have ran the test on traditional linux filesystems (`ext4`, `btrfs`, `tmpfs`) and `libfuse` based filesystems (`encfs`, `s3ql`) and everything works correctly. On the other hand, the test fails on all `go-fuse` based filesystems I tried (`loopback`, `zipfs`, `gocryptfs`).

    /* file: ls-count.c */
    /* compile with: gcc -Wall -O2 -lrt ls-count.c -o ls-count */
    
    #include <stddef.h>
    #include <stdlib.h>
    #include <errno.h>
    #include <stdio.h>
    #include <sys/types.h>
    #include <dirent.h>
    #include <signal.h>
    #include <time.h>
    #include <string.h>
    
    /* return the count of files contained in the directory at path */
    unsigned long count_dir_entries(const char *path) {
    	unsigned long result = 0;
    	DIR *dirp = opendir(path);
    	if (dirp == NULL) {
    		perror("ls-count");
    		exit(1);
    	}
    	while (1) {
    		errno = 0;
    		if (readdir(dirp) == NULL) {
    			if (errno != 0) {
    				closedir(dirp);
    				perror("ls-count");
    				exit(1);
    			}
    			break;
    		}
    		result++;
    	}
    	closedir(dirp);
    	return result;
    }
    
    void signal_handler(int signum) {
    	/* do nothing */
    }
    
    int main(int argc, char *argv[]) {
    	if (argc != 2) {
    		fprintf(stderr, "ls-count: wrong number of arguments\n");
    		exit(1);
    	}
    
    	struct sigaction act;
    	memset(&act, 0, sizeof(struct sigaction));
    	sigemptyset(&act.sa_mask);
    	act.sa_handler = signal_handler;
     	if (sigaction(SIGVTALRM, &act, NULL) != 0) {
    		perror("ls-count");
    		exit(1);
    	}
    
    	/* create a timer */
    	timer_t timerid;
    	struct sigevent sev;
    	sev.sigev_notify = SIGEV_SIGNAL;
    	sev.sigev_signo = SIGVTALRM;
    	if (timer_create(CLOCK_MONOTONIC, &sev, &timerid) != 0) {
    		perror("ls-count");
    		exit(1);
    	}
    
    	/* arm the timer */
    	struct itimerspec timer_value;
    	timer_value.it_interval.tv_sec = 0;
    	timer_value.it_interval.tv_nsec = 10000000;
    	timer_value.it_value.tv_sec = 0;
    	timer_value.it_value.tv_nsec = 10000000;
    	if (timer_settime(timerid, 0, &timer_value, NULL) != 0) {
    		perror("ls-count");
    		exit(1);
    	}
    
    	/* run the loop */
    	unsigned long count = count_dir_entries(argv[1]);
    	while (1) {
    		unsigned long count2 = count_dir_entries(argv[1]);
    		if (count != count2) {
    			fprintf(stderr, "ls-count: counts do not match: %lu vs %lu\n", count, count2);
    			exit(2);
    		}
    	}
    
    	return 0;
    }

**Comment by redneb** [comment] 2017-10-15 19:13
For a little background on this, I encountered this issue with a program I wrote in haskell. The problem is that `ghc` (the de facto haskell compiler) uses `SIGVTALRM` to make its green threads behave more preemptively. But `go-fuse` doesn't like that and calling [getDirectoryContents](https://hackage.haskell.org/package/directory/docs/System-Directory.html#v:getDirectoryContents) on a directory that resides in a `go-fuse` filesystem returns inconsistent results.

**Comment by rfjakob** [comment] 2017-10-15 21:16
Excellent bug report @redneb! I can reproduce this with gocryptfs. I have moved the initial count up to before the timer is started to get a stable initial count ([code](https://gist.github.com/rfjakob/79581292a037ae7cb068067cb6207ef8)). I get this output: 
```
$ while sleep 1; do ./ls-count b ; done
ls-count: counts do not match: 10002 vs 9993
ls-count: counts do not match: 10002 vs 9994
ls-count: counts do not match: 10002 vs 9993
ls-count: counts do not match: 10002 vs 9993
ls-count: counts do not match: 10002 vs 9994
ls-count: counts do not match: 10002 vs 9995
ls-count: counts do not match: 10002 vs 9993
ls-count: counts do not match: 10002 vs 9994
ls-count: counts do not match: 10002 vs 9994
ls-count: counts do not match: 10002 vs 9994
```

**Comment by hanwen** [comment] 2017-10-16 22:00
looks like this has something to do with readdirplus. If one removes CAP_READDIRPLUS go-fuse works correctly.

can you confirm that the libfuse examples you tried are using READDIRPLUS too?

**Comment by hanwen** [comment] 2017-10-16 22:29
it also reproduces nicely on an empty dir (the . and .. entries should generate 2 entries)

on the FUSE side we see

00:27:42.186726 Dispatch 885: READDIRPLUS, NodeId: 1. data: {Fh 2 off 0 sz 4096  L 0 NONBLOCK,DIRECTORY,0x8000} 
00:27:42.186737 Serialize 885: READDIRPLUS code: OK value:  320 bytes data

00:27:42.186904 Dispatch 886: READDIRPLUS, NodeId: 1. data: {Fh 2 off 2 sz 4096  L 0 DIRECTORY,NONBLOCK,0x8000} 
00:27:42.186919 Serialize 886: READDIRPLUS code: OK value: 
00:27:42.187006 Dispatch 887: RELEASEDIR, NodeId: 1. data: {Fh 2 NONBLOCK,DIRECTORY,0x8000  L0} 
00:27:42.187021 Serialize 887: RELEASEDIR code: OK value: 

ie. 2 entries were shipped to the kernel.

userland says:

open("/tmp/x", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0775, st_size=40, ...}) = 0
getdents(3, /* 2 entries */, 32768)     = 48
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
open("/tmp/x", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0775, st_size=40, ...}) = 0
getdents(3, /* 1 entries */, 32768)     = 24
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=1005606600, ptr=0x7f853bf056c8}} ---
rt_sigreturn({mask=[]})                 = 24
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
write(2, "ls-count: counts do not match: 2"..., 38ls-count: counts do not match: 2 vs 1
) = 38
exit_group(2)                           = ?
+++ exited with 2 +++

looks like a kernel bug.

**Comment by rfjakob** [comment] 2017-10-18 17:14
More evidence for the kernel bug: I can reproduce this with libfuse's [passthrough example](https://github.com/libfuse/libfuse/blob/master/example/passthrough_fh.c).

**Comment by hanwen** [comment] 2017-10-19 11:16
is this a showstopper, btw? I could add some option to disable readdirplus using a MountOption.

**Comment by rfjakob** [comment] 2017-10-19 11:40
I think we need the option, question is if we should default to off as well

**Comment by rfjakob** [comment] 2017-10-20 09:41
@hanwen you good with using this ticket to track progress on a kernel fix as well? I'll be posting to lkml and friends.

**Comment by hanwen** [comment] 2017-10-20 10:42
of course, go ahead.

**Comment by rfjakob** [comment] 2017-10-24 18:15
Posted as https://marc.info/?l=linux-kernel&m=150886866125971&w=2 .

**Comment by rfjakob** [comment] 2017-10-25 18:53
That was quick! Miklos Szeredi has posted a patch that fixes the issue: https://patchwork.kernel.org/patch/10026215/

**Comment by rfjakob** [comment] 2017-10-28 19:18
Merged to mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs?id=c6cdd51404b7ac12dd95173ddfc548c59ecf037f

**Comment by redneb** [comment] 2017-11-12 00:39
The patch is included in stable (4.13.11) and longterm (4.9.60, 4.4.96, 4.1.46, 3.18.79) kernels. So I think there is no need for a mount option to disable readdirplus. I guess we can close this one.

**Comment by rfjakob** [comment] 2017-11-12 09:14
Have distros picked it up  already?

**Comment by hanwen** [comment] 2017-12-06 21:22
I'm closing this issue since it is not really a go-fuse problem.

**Closed by hanwen** 2017-12-06 21:22 UTC
