### ISSUE TITLE
Enable Trash on macOS

### ISSUE THREAD

**Issue by eugenesvk** [hanwen/go-fuse#183] opened 2017-09-05 20:55 UTC
I'm using [GoCryptFS](https://github.com/rfjakob/gocryptfs), which relies on your library for file system operations.
Is there a way to enable macOS trash functionality for FUSE volumes? Otherwise it's rather inconvenient to have those constant verification popups on every delete operation.
Thanks

**Comment by pmalhaire** [comment] 2017-09-21 06:46
@eugenesvk normaly you can add the trash by creating the .trashes with the correct rights and attrs.

**Comment by eugenesvk** [comment] 2017-09-26 15:34
Thanks for the suggestion. I've copied my user **.Trashes** folder to the mounted drive (that should handle the correct rights and attrs, right?), but it didn't change anything, Finder still deletes files permanently (with a warning). Is there more to it?

**Comment by pmalhaire** [comment] 2017-09-27 07:07
Let me try I may have forgoten an other needed hook.

**Comment by pmalhaire** [comment] 2017-09-27 09:13
Actually there is a bug somewhere hard to know where as for now.

.Trash or .Trashes should use 0333 rights with root:wheel as user 

I got : 
chown -R root:wheel .Trash
chown: .Trash: Permission denied
chown: .Trash: Operation not permitted

**Comment by rfjakob** [comment] 2017-09-27 11:12
Maybe chown the encrypted directory? (compare inode numbers to see what is what)

**Comment by pmalhaire** [comment] 2017-09-27 11:19
@rfjakob what I was saying is that I could not get the trash working properly with go-fuse only (I am using macOS 10.13).

**Comment by pmalhaire** [comment] 2017-09-27 12:33
I made the system calls for both and there is nothing clear in the finder calls but still they are not the same the problem is probably in the way the mountpoint is mounted.

The best way to find out it to go down to the osxfuse layer.

for both way(trough mountpoint and through osxfuse volume) I did : 

```bash
 sudo fs_usage Finder >| /tmp/test_volume
```

[test_mountpoint.txt](https://github.com/hanwen/go-fuse/files/1337081/test_mountpoint.txt)
[test_volume.txt](https://github.com/hanwen/go-fuse/files/1337082/test_volume.txt)

**Comment by pmalhaire** [comment] 2017-09-27 12:54
In short I don't know since when but the Trash system has changed and it seems that osxfuse need some update to make it work. 

It's not a bug, it's a behavior change in macOS 10.13 and probably before considering [this comment]([url](https://github.com/osxfuse/osxfuse/issues/246#issuecomment-268195295)) 

@eugenesvk which macOS version are you using ?

**Comment by eugenesvk** [comment] 2017-09-27 13:39
@pmalhaire mine is **10.12.6 (16G29)**
I have the same error on a GoCryptFS volume **DocG**
```
mnt/DocG > chown -R root:wheel .Trash
chown: changing ownership of '.Trash': Operation not permitted
```

And with **sudo**
```
mnt/DocG > sudo chown -R root:wheel .Trash
Password:
chown: cannot read directory '.Trash': No such file or directory
```

**Comment by eugenesvk** [comment] 2017-09-28 10:40
@pmalhaire cool, thanks for testing and finding out the issue! Hopefully the osxfuse will be able to fix it

**Comment by hanwen** [comment] 2018-05-08 07:37
closing this for now, since it seems not be an issue in go-fuse

**Closed by hanwen** 2018-05-08 07:37 UTC
